//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOnline2.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Direcciones = new HashSet<Direccion>();
            this.Emails = new HashSet<Email>();
            this.Telefonos = new HashSet<Telefono>();
            this.Webs = new HashSet<Web>();
            this.ProductosVendidos = new HashSet<ProductoVendido>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string CUIL { get; set; }
        public string CUIT { get; set; }
        public string Notas { get; set; }
        public byte[] Imagen { get; set; }
        public bool Favorito { get; set; }
    
        public virtual ICollection<Direccion> Direcciones { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Telefono> Telefonos { get; set; }
        public virtual ICollection<Web> Webs { get; set; }
        public virtual ICollection<ProductoVendido> ProductosVendidos { get; set; }
    }
}
