//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOnline2.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public int Cliente_ID { get; set; }
    
        public virtual Cliente Cliente { internal get; set; }
    }
}
