SET IDENTITY_INSERT [dbo].[Productos] ON
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1007, N'ABC x 5 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1008, N'ABC x 1 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1009, N'ABC x 2,5 Kgs', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1010, N'ABC x 10 Kgs', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1011, N'ABC x 25 Kgs', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1012, N'ABC x 70 Kgs', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1013, N'ABC x 50 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1014, N'CO2 x 1 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1015, N'CO2 x 3,5 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1016, N'CO2 x 5 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1017, N'CO2 x 7 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1018, N'CO2 x 10 Kgs.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1019, N'H2O x 10 Lts.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1020, N'Halon x 2,5 KG', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1021, N'CO2 x 25 Kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1022, N'Indefinido', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1023, N'Halon x 5 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1024, N'Halon x 1 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1025, N'Halon x 10 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1026, N'H2O x 100 Lts.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1027, N'CO2 x 2 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1028, N'ABC x 100 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1029, N'CO2 x 20 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1030, N'ABCK x 6 lts.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1031, N'ABCK x 10 Lts.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1032, N'CO2 x 1/2 kg.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1033, N'CO2 x 1/4 kg.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1034, N'Espuma x 10 Lt.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1035, N'Espuma x 100 Lt.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1036, N'ABC x 6 kg', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1037, N'H2O x 25 lt', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1038, N'Espuma x 50 Lts.', 12, <SQLVARIANT>)
INSERT INTO [dbo].[Productos] ([ID], [Nombre], [Vencimiento], [Imagen]) VALUES (1039, N'ABC x 2', 12, <SQLVARIANT>)
SET IDENTITY_INSERT [dbo].[Productos] OFF
