SELECT 
DOMICILIOS.DOM_ID, 
DOMICILIOS.DOM_CLIENTE_ID, 
(DOMICILIOS.DOM_CALLE &  "  "  & DOMICILIOS.DOM_ALTURA & " ,"  & DOMICILIOS.DOM_LOCALIDAD) as Direccion,
'Unica' as Tipo
FROM DOMICILIOS
WHERE DOMICILIOS.DOM_FECHA_BAJA='No';
