SELECT DISTINCT CLIENTES.CLI_ID, 'CELULAR' AS TIPO ,CLIENTES.CLI_TELEFONO1 AS NUMERO
FROM CLIENTES
WHERE ( CLIENTES.CLI_TELEFONO1 <>'' AND CLIENTES.CLI_TELEFONO1 <>'0' AND CLIENTES.CLI_TELEFONO1 <>'-')
AND CLIENTES.CLI_FECHA_BAJA='No'
UNION
SELECT DISTINCT CLIENTES.CLI_ID, 'CELULAR' AS TIPO ,CLIENTES.CLI_TELEFONO2
FROM CLIENTES
WHERE ( CLIENTES.CLI_TELEFONO2 <>'' AND CLIENTES.CLI_TELEFONO2 <>'0' AND CLIENTES.CLI_TELEFONO2 <>'-')
AND CLIENTES.CLI_FECHA_BAJA='No';